### ISSUE TITLE
Will this work on a DELL-latitude-7285 with 8GB memory (instead of the 16GB listed in the Git Spec)?

### ISSUE THREAD

**Issue by cangman013** [xqmnig/DELL-latitude-7285-OS-X#1]
I've been trying to get this to work on a Dell 7285 with 8GB of memory (all other specs as listed in the Git post).  Both the Clover and OpenCore versions that are posted hang during the boot loading process--the boot loader never kernel panics, but it also never makes it to the "Apple" screen, or MacOS login screen.  I have set the DVMT prealloc to 64MB and disabled MSR lock as noted in the BIOS Setup in the ReadMe.  I've been trying to get this to work for a few days now, no joy.  I would appreciate any helpful direction that you might provide.

**Comment by xqmnig** [comment]
I used to use Dell's 7285 i7 8GB, and clover can run on 8GB machines. This version of clover can boot to the apple login interface. If it is the first time to install it, please add - V to bootagr, or turn off igpu injection in clover. After installation, if you can enter the system normally. You can remove - V and turn on igpu injection.

**Comment by cangman013** [comment]
Many thanks, xqmnig.

It turns out that I was able to get it working.  I missed a BIOS uncheck in your instructions (as soon as I cleared the UEFI Legacy Boot, everything worked as you said it would).

Thank you for posting this very helpful Clover and OpenCore package for the Dell 7285 (you saved me about two weeks of development effort).

Cangman

**Comment by cangman013** [comment]
xqmnig,
Does the internal display wake for you after sleep?  I can't get that to work.  External display(s) will wake after sleep, but the internal display appears to have the backlight come on, but no image [a black screen with backlight].  I've tried many of the suggested remedies to this, but no success.
Thanks.
cangman

**Comment by iBerioni** [comment]
please remove the video instruction

**Comment by iBerioni** [comment]
please make a video instruction
